//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace File_Upload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class My_File
    {
        public My_File()
        {
            this.Project_defect = new HashSet<Project_defect>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public byte[] TotalColumns { get; set; }
    
        public virtual ICollection<Project_defect> Project_defect { get; set; }
    }
}
