//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace File_Upload.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Project_defect
    {
        public int PID { get; set; }
        [Required]
        public string Project { get; set; }
        public string Key { get; set; }
        public string Summary { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public string Resolution { get; set; }
        public string Assignee { get; set; }
        public string Reporter { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> Resolved { get; set; }
        public string Affects_Vesrsion { get; set; }
        public string Fix_Version { get; set; }
        public string Components { get; set; }
        public string Time_spent { get; set; }
        public string Test_Cycle { get; set; }
        public string Reopens { get; set; }
        public string Root_Cause { get; set; }
        public string QA_Team { get; set; }
        public string Dev_Team { get; set; }
        public int Id { get; set; }
    
        public virtual My_File My_File { get; set; }
    }
}
